version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    build: ./keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_container:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    depends_on:
      - postgres

  server:
    build: ./server
    environment:
      keycloakIp: keycloak
      clientId: "shai"
      clientSecret: "secret"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
